name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        run: npm install

      #- name: lint
      #  run: npm run eslint

      - name: build
        run: npm run build

      #- name: test
      #  run: npm test

      #- name: e2e tests
      #  uses: cypress-io/github-action@v2
      #  with:
      #    start: npm run start-prod
      #    command: npm run test:e2e
      #    wait-on: http://localhost:5000
      #    spec: cypress/integration/*.js

      - name: deploy
        uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "fullstackopencicd"
          heroku_email: "saleh-rz@outlook.com"
          remote_branch: master
          healthcheck: "https://fullstackopencicd.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

jobs:
  versioning:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:

    - uses: actions/checkout@v2

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch